[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 1. Rutas de cabeceras (.h) y Variables globales
build_flags =
    -DBOARD_ESP32
    -Isrc
    -I../shared/config
    -I../shared/layer1_hal
    -I../shared/layer2_drivers
    -I../shared/layer3_robotics
    -I../shared/layer4_app

; 2. Archivos fuente (.c / .cpp) a compilar
build_src_filter =
    +<*>
    +<../../shared/layer2_drivers/*.c>
    +<../../shared/layer2_drivers/*.cpp>
    +<../../shared/layer3_robotics/*.c>
    +<../../shared/layer4_app/*.c>

; 3. Librerías externas
lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4