[platformio]
default_envs = esp32dev

[env:base]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DBOARD_ESP32
    -Isrc
    -I../shared/config
    -I../shared/layer1_hal
    -I../shared/layer2_drivers
    -I../shared/layer3_app

[env:esp32dev]
extends = env:base
build_src_filter =
    +<*>
    -<tests/>
    +<../../shared/layer2_drivers/*.c>
    +<../../shared/layer2_drivers/*.cpp>
    +<../../shared/layer3_app/*.c>

lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4

[env:imu_only]
extends = env:base
build_src_filter =
    +<layer1_hal/hal_imu_esp32.cpp>
    +<layer1_hal/hal_time_esp32.cpp>
    +<tests/imu_only.cpp>
    +<../../shared/layer2_drivers/driver_mpu6050.c>

[env:tof_only]
extends = env:base
build_src_filter =
    +<layer1_hal/hal_tof_esp32.cpp>
    +<tests/tof_only.cpp>
    +<../../shared/layer2_drivers/driver_distancia.c>

lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4
